### ISSUE TITLE
Documentation homepage issues

### ISSUE THREAD

**Issue by olaf-k** [Vonage/vivid-3#935]
- [x] The landing page mixes too many topics and should be split (#940)
- [x] More code samples, less explanations/justifications (#940)
- [x] Update broken links / fix incorrect ones (#937)
- [ ] Navigation could be improved (#788 damn you stalebot).

+ personal / subjective issues:
- [ ] The font size is too tiny.
- [ ] Text should flow freely, the width constraint looks weird on wide screens.

See also #766 and and #790

**Comment by yinonov** [comment]
> * [ ]  The landing page mixes too many topics and should be split.
> * [ ]  More code samples, less explanations/justifications.
> * [x]  Update broken links / fix incorrect ones.
> * [ ]  Navigation could be improved ([[docs] navigating should not reload the entire page #788](https://github.com/Vonage/vivid-3/issues/788) damn you stalebot).
> 
> * personal / subjective issues:
> 
> * [ ]  The font size is too tiny.

by design

> * [ ]  Text should flow freely, the width constraint looks weird on wide screens.

characters should be limited to 64 I believe. but this can be revisited
